export const LOADING_RESULTS = 'LOADING_RESULTS';
export const RECEIVE_RESULTS = 'RECEIVE_RESULTS';
export const RESET_RESULTS = 'RESET_RESULTS';
export const FILTER_RESULTS = 'FILTER_RESULTS';
export const STORE_REPO = 'STORE_REPO';
export const STORE_FILTERED_REPO = 'STORE_FILTERED_REPO';